const Projects = {
    Details:{//adding in opposite-chronological order, so it's easy to add later    
        Template: {
            ID: "Template",
            Name: "",
            SmallDescription: "",
            LargeDescription: "",
            DownloadLink: "",
            EmbedVideoLinkID: "",
            NoOfProjectImages: 1
        },
        WorkInProgress: {
            ID: "WorkInProgress",
            Name: "Work In Progress",
            SmallDescription: "iOS, Android, AI",
            LargeDescription: "Have you heard my Under Construction joke?<br>It's not done yet",
            NoOfProjectImages: 1
        },
        TileVisualiser: {
            ID: "TileVisualiser",
            Name: "Tile Visualiser",
            SmallDescription: "Shaders, Occulus Go, Unity3D",
            LargeDescription: ' • Wrote Surface Shader from scratch in Cg/HLSL (Unity3D) for VR Occulus Go build<br> • Proposed most opptimised way to approach a problem keeping in mind the target platform<br> • Set-up Unity3D for most optimised yet best quality settings<br> • Helped to build realistic Tile Visualiser with dynamic tiles and patterns with different grout<br>',
            DownloadLink: "",
            EmbedVideoLinkID: "",
            NoOfProjectImages: 0
        },
        // ShiroDash: {
        //     ID: "ShiroDash",
        //     Name: "Shiro Dash",
        //     SmallDescription: "Published Android Game, 2D, C#",
        //     LargeDescription: "• 2D Infinite runner with jump and dash mechanics in Unity3D and C# for Android.<br>• Platforms are autogenerated with tweakable values of distance given to designers.<br>• Speed of the character increases with respect to time based on formula provided by the designers.<br>• Worked on implementation of Spline animation of character, UI, design.<br>",
        //     DownloadLink: "https://play.google.com/store/apps/details?id=com.tp.shirodash",
        //     EmbedVideoLinkID: "",
        //     NoOfProjectImages: 5
        // },
        Snake3D: {
            ID: "Snake3D",
            Name: "Horse 3D",
            SmallDescription: "Published Android Game, C#, Unity3D",
            LargeDescription: 'In this horse game, each of your horses deserves its very own special equipment! Discover various saddles, pads, bridles and leg wraps. Customize your mighty steed’s mane according to your taste! Happy with your new equestrian gear? Then make the most of it at the next tournament!  If the tracks of this horse game become too easy, we have the perfect solution for you: build your own courses! With our building tool, you can easily create tracks and obstacle courses for your own equestrian tournaments.',
            DownloadLink: "https://play.google.com/store/apps/details?id=com.CosmicTurtles.Snake3D",
            EmbedVideoLinkID: "0GcFrCnOaTA",
            NoOfProjectImages: 7
        },        
        Homography: {
            ID: "Homography",
            Name: "Reactive Display for VR",
            SmallDescription: "IGGO 2017 (IEEE Publication)",
            LargeDescription: 'The feeling of presence in virtual reality has enabled a large number of applications. These applications typically deal with 360° content. However, a large amount of existing content is available in terms of images and videos i.e 2D content. Unfortunately, these do not react to the viewer position or motion when viewed through a VR Head Mount Device.<br><br>Thus in this work, we propose reactive displays for VR which instigate a feeling of discovery while exploring 2D content. We create this by taking into account user position and motion to compute homography based mappings that adapt the 2D content and re-project it onto the display. This allows the viewer to obtain a more richer experience of interacting with 2D content similar to the effect of viewing through the window at a scene. We also provide a VR interface that uses a constrained set of reactive displays to easily browse through 360° content.<br><br>The proposed interface tackles the problem of nausea caused by existing interfaces like photospheres by providing a natural room-like intermediate interface before changing 360° content. We perform user studies to evaluate both of our interfaces. The results show that the proposed reactive display interfaces are indeed beneficial.',
            DownloadLink: "https://ieeexplore.ieee.org/document/8088450/",
            EmbedVideoLinkID: "HNwwBkMFFIE",
            NoOfProjectImages: 7
        },
        Gameplay: {
            ID: "Gameplay",
            Name: "Pet Runners",
            SmallDescription: "Published Android Game, C#, Unity3D",
            LargeDescription: "A cat running game! Take care of your dog, puppy or kitten. Play virtual dog games with toys, decorate your pet house in this simulator or dress up cute pets and adopt or rescue more. Pet Run is the best free running game where you can meet your new best friend and go for a run! Choose your pet pal and dash your way through the city and park for fun running adventures! ",
            DownloadLink: "",
            EmbedVideoLinkID: "",
            NoOfProjectImages: 6
        },
        NearbyConnections: {
            ID: "NearbyConnections",
            Name: "Nearby Connections",
            SmallDescription: "Android API, C#, java, Bluetooth",
            LargeDescription: 'Built a communication layer which uses Bluetooth API and Nearby Connections API for offline and Nearby Messages API for online communication. Created an android plugin for unity using Android Studios to add the core Android, which Unity does not have built in. Used Bluetooth for close - range communication, Nearby Connections for mid - range connections(with or without internet) and Nearby Messages for long - range connection.Bluetooth Communication layer uses device inbuilt Bluetooth hardware to connect and send / receive data, Nearby Connections uses local Wi - Fi for connections while Nearby Messages uses Google Cloud for communication.This SDK can also handle different disconnection cases and react accordingly.Sending and receiving are done via array of bytes which is later converted into game state.<br><br> •Developed SDK for Unity3D, framework to develop multiplayer games which uses Bluetooth, Wi - Fi connections for communication<br> •Integrated this plugin with Unity3D and tested it by building an online - offline turn - based multiplayer first - person shooter game<br> •This game is a Turn - based Multiscreen Multiplayer game where a player has to shoot other players and the last player standing wins<br> •Used language: C# & java, Software: Unity3D & Android Studios and API: Bluetooth, Nearby Connections & Nearby Messages',
            DownloadLink: "",
            EmbedVideoLinkID: "",
            NoOfProjectImages: 7
        },
        MREncyclopedia: {
            ID: "MREncyclopedia",
            Name: "Mixed Reality Encyclopedia",
            SmallDescription: "VR-AR, Google Cardboard, Microsoft",
            LargeDescription: 'App developed at Microsoft code.fun.do organised by Microsoft, using Unity3D for Google Cardboard. Aim was to develop an App which focuses on Dynamic Teaching-Learning tools to make learning more interesting for students and for teachers to identify gaps and improve methods for teaching.<br><br>• Virtual and augmented reality based encyclopedia for Google Cardboard built using Unity3D for education and teaching purpose <br>• Gathered data from NASA, Wikipedia and Nat Geo documentaries to recreate scaled model of Solar System in virtual space<br>• Designed 3D environment of all planets of the Solar System and included a feature to view surroundings of the planets using Google Cardboard in VR environment<br>• Can be used to teach almost all topics of any subject and can be modified to a full-fledged Encyclopedia<br>• App was built in 24-hour hackathon, Code.fun.do organized by Microsoft',
            DownloadLink: "",
            EmbedVideoLinkID: "58QLQCEOeGo",
            NoOfProjectImages: 10
        },
        ChemicalCarriageway: {
            ID: "ChemicalCarriageway",
            Name: "With Puppy",
            SmallDescription: "Published Android Game, C#, Unity3D, Colyseus",
            LargeDescription: 'With Puppy is play to earn style mobile game designed to encourage players to exercise. Server is build by colyseus.',
            DownloadLink: "https://play.google.com/store/apps/details?id=com.Blinds_FaithCC.ChemicalCarriageway",
            EmbedVideoLinkID: "LvCkvSatLFs",
            NoOfProjectImages: 5
        },
        // RiTE: {
        //     ID: "RiTE",
        //     Name: "RiTE",
        //     SmallDescription: "PC game, Js, Unity 3D",
        //     LargeDescription: 'PC stanalone Window platform- Game<br>RiTE-Race it Till the End is a 3D Game built on unity3D platform for windows standalone platform. A 2 month project under Programming Club, IIT Kanpur <br><br>• Programmed and designed 3D racing, shooting and survival indie game for Windows platform using JavaScript<br>• Gameplay: Complete Lap race, Death match, Timed race & Survival game<br>• Applied concepts of Laws of Motion, Vectors and Calculus, AI Cars, Aesthetic and non-Aesthetic Designing, Physics Raycast and many more<br>• Artificial Intelligence for opponent cars is based on original logic of automated car, used in Google driverless cars',
        //     DownloadLink: "",
        //     EmbedVideoLinkID: "",
        //     NoOfProjectImages: 6
        // },
    }
};